CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [AuthUserId] NVARCHAR(128) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULl,
	[EmailAddress] NVARCHAR(256) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT getutcdate()
)
